### ISSUE TITLE
Moving away from Github Pages

### ISSUE THREAD

**Issue by kieraneglin** [gridfinity-unofficial/gridfinity-unofficial.github.io#19]
Github Pages is a great free resource, but ultimately it's pretty limited in what it can do. I see you've already created a [placeholder repo](https://github.com/gridfinity-unofficial/website) for an eventual migration away from GH Pages so it appears to be on your roadmap anyway!

I'm a fan of the Gridfinity project and appreciate what you've done with this site, so I'd like to give back! I'd like to propose a few things and hear your thoughts:

- I'd like to fork the Gridfinity placeholder repo and start creating a fully-fledged website. I'd prefer to use Rails just for dev speed, but I have a lot of experience with JS/TS, Elixir, and Rust as well
- If my fork is accepted, I'd like to pay for some level of hosting for 6-12 months

Please let me know what you think! I'm not much of a design guy, but I have a lot of experience in server-side in general/client-side JS.

**Comment by icorbrey** [comment]
Since I don't think this really requires a full stack, what if we hosted this on Netlify? Static sites (including things built with JS frameworks like React and Svelte) can be hosted for free and it's what I've been using for a while.

**Comment by kieraneglin** [comment]
My initial intent was to allow things like easier CRUD actions around managing models, allowing for some sort of submission process, potentially enabling API integrations or scrapers, stuff like that. 

However, I'll be closing this issue due to lack of interest
